### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by Fastidious** [Tethik/burn-after-reading#21]
When visiting a message, the visitor will show "Invalid date" under the time column. Tried it on the provided demo only.

**Comment by Tethik** [comment]
Thanks for the report! I tried it myself just now and it works ok, so I'm guessing it could be a localization issue.

Just a fyi tho is that this project is kind of old. I'm hoping to do a fresh rewrite of it. Thanks for testing it out though. If you need any help, let me know :)

**Comment by Fastidious** [comment]
Will keep my eyes on the rewrite then. Thanks!
