### ISSUE TITLE
Tooltips do not work

### ISSUE THREAD

**Issue by frankenstein91** [Tethik/burn-after-reading#23]
I looked at your demo page for this project today. I found two pictures there which I didn't understand at first sight.  I couldn't see any text in the GUI, so I looked into the source code. There you use the attribute "tooltip" to give more information on how to use the checkbox. According to my tests with the debug function of Firefox and knowledge search in the HTML standard, you should use the "title" function to get a working tooltip. I hope this tip helps you to improve your project.

**Comment by Tethik** [comment]
Thanks for your feedback, to be honest I'm just happy that someone had a look at the project :)

I changed the attribute to "title" as you suggested and added a text to label the option better. I will update the demo shortly.

**Comment by frankenstein91** [comment]
looks good thank you
